// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

type Session struct {
	Token  interface{} `json:"token"`
	Data   []byte      `json:"data"`
	Expiry interface{} `json:"expiry"`
}

type User struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
}
