// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package models

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, password, created_at
) VALUES (
  ?, ?, ?
)
RETURNING id, username, password, created_at
`

type CreateUserParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password, created_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, username, password, created_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, created_at FROM users
ORDER BY username
`

type ListUsersRow struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.ID, &i.Username, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnGasIncomeHistory = `-- name: ReturnGasIncomeHistory :many
SELECT income, change_timestamp FROM gas_income_history
WHERE user_id = ?
`

type ReturnGasIncomeHistoryRow struct {
	Income          int64 `json:"income"`
	ChangeTimestamp int64 `json:"change_timestamp"`
}

func (q *Queries) ReturnGasIncomeHistory(ctx context.Context, userID int64) ([]ReturnGasIncomeHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, returnGasIncomeHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnGasIncomeHistoryRow
	for rows.Next() {
		var i ReturnGasIncomeHistoryRow
		if err := rows.Scan(&i.Income, &i.ChangeTimestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnMetalIncomeHistory = `-- name: ReturnMetalIncomeHistory :many
SELECT income, change_timestamp FROM metal_income_history
WHERE user_id = ?
`

type ReturnMetalIncomeHistoryRow struct {
	Income          int64 `json:"income"`
	ChangeTimestamp int64 `json:"change_timestamp"`
}

func (q *Queries) ReturnMetalIncomeHistory(ctx context.Context, userID int64) ([]ReturnMetalIncomeHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, returnMetalIncomeHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReturnMetalIncomeHistoryRow
	for rows.Next() {
		var i ReturnMetalIncomeHistoryRow
		if err := rows.Scan(&i.Income, &i.ChangeTimestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGasIncomeHistory = `-- name: UpdateGasIncomeHistory :exec
INSERT INTO gas_income_history(
    income, user_id, change_timestamp
) VALUES (
?, ?, ?
)
`

type UpdateGasIncomeHistoryParams struct {
	Income          int64 `json:"income"`
	UserID          int64 `json:"user_id"`
	ChangeTimestamp int64 `json:"change_timestamp"`
}

func (q *Queries) UpdateGasIncomeHistory(ctx context.Context, arg UpdateGasIncomeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateGasIncomeHistory, arg.Income, arg.UserID, arg.ChangeTimestamp)
	return err
}

const updateMetalIncomeHistory = `-- name: UpdateMetalIncomeHistory :exec
INSERT INTO metal_income_history(
    income, user_id, change_timestamp
) VALUES (
?, ?, ?
)
`

type UpdateMetalIncomeHistoryParams struct {
	Income          int64 `json:"income"`
	UserID          int64 `json:"user_id"`
	ChangeTimestamp int64 `json:"change_timestamp"`
}

func (q *Queries) UpdateMetalIncomeHistory(ctx context.Context, arg UpdateMetalIncomeHistoryParams) error {
	_, err := q.db.ExecContext(ctx, updateMetalIncomeHistory, arg.Income, arg.UserID, arg.ChangeTimestamp)
	return err
}
