FROM golang:1.23.3-alpine AS builder

WORKDIR /app

COPY . ./

RUN go build -o frogfoot-client./cmd/client/main.go

FROM golang:1.23.3-alpine

COPY --from=builder /app/frogfoot-client /app/frogfoot-client

CMD ["/app/frogfoot-client"]
