name: Build and Push server container

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["server","client"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Build server
        run: go build -o tmp/frogfoot-${{ matrix.type }} cmd/${{ matrix.type }}/main.go

  container:
    name: Container
    needs: [build]
    if: ${{ github.ref == 'refs/head/main' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: ["server","client"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile-${{ matrix.type }}
          push: true
          tags: fulcrum29/frogfoot-${{ matrix.type }}:latest
